name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and Push Docker Image
      run: |
        docker build -t react-app .
        docker save react-app > react-app.tar

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ubuntu
      run: |
        scp -i $SSH_PRIVATE_KEY react-app.tar $USER@$HOST:~/
        ssh -i $SSH_PRIVATE_KEY $USER@$HOST << EOF
          docker load < react-app.tar
          docker stop react-app || true
          docker rm react-app || true
          docker run -d --name react-app -p 80:80 react-app
        EOF
